export const LOCATION_LIST_LIST_SLICE = "LOCATION_LIST_LIST_LIST_SLICE";
export const LOCATION_LIST_LIST_LIST_THUNK = "LOCATION_LIST_LIST_LIST_THUNK";

export const FACILITIES_LIST_LIST_SLICE = "FACILITIES_LIST_LIST_LIST_SLICE";
export const FACILITIES_LIST_LIST_LIST_THUNK = "FACILITIES_LIST_LIST_LIST_THUNK";