export const AUTH_LOGIN_SLICE = "AUTH_LOGIN_LIST_SLICE";
export const AUTH_LOGIN_THUNK = "AUTH_LOGIN_THUNK";

export const AUTH_REGISTER_SLICE = "AUTH_REGISTER_SLICE";
export const AUTH_REGISTER_THUNK = "AUTH_REGISTER_THUNK";

export const CENTERS_LIST_SLICE = "CENTERS_LIST_SLICE";
export const CENTERS_LIST_THUNK = "CENTERS_LIST_THUNK";

export const FACILITIES_LIST_SLICE = "FACILITIES_LIST_SLICE";
export const FACILITIES_LIST_THUNK = "FACILITIES_LIST_THUNK";

export const CREATE_BOOKING_SLICE = "CREATE_BOOKING_SLICE";
export const CREATE_BOOKING_THUNK = "CREATE_BOOKING_THUNK";

export const UPDATE_BOOKING_SLICE = "UPDATE_BOOKING_SLICE";
export const UPDATE_BOOKING_THUNK = "UPDATE_BOOKING_THUNK";

export const VIEW_BOOKINGS_LIST_SLICE = "VIEW_BOOKINGS_LIST_SLICE";
export const VIEW_BOOKINGS_LIST_THUNK = "VIEW_BOOKINGS_LIST_THUNK";

export const DELETE_BOOKING_SLICE = "DELETE_BOOKING_SLICE";
export const DELETE_BOOKING_THUNK = "DELETE_BOOKING_THUNK";

export const SLOT_AVAILABILITY_SLICE = "SLOT_AVAILABILITY_SLICE";
export const SLOT_AVAILABILITY_THUNK = "SLOT_AVAILABILITY_THUNK";
